# Generated by Django 2.2.12 on 2020-05-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('ip', models.CharField(default='', max_length=200)),
                ('mac', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
