# Generated by Django 2.2.12 on 2020-05-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='ip',
            new_name='destination_country',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='mac',
            new_name='destination_ip',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='destination_mac',
        ),
        migrations.AddField(
            model_name='device',
            name='destination_port',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='host',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='packets_length',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='protocol',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='source_ip',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='source_mac',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='source_port',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterModelTable(
            name='device',
            table='device',
        ),
    ]
